Description of doColorMap
Home > SuperSeggerRelease > viz > doColorMap.m
doColorMap
PURPOSE
doColorMap : ?
SYNOPSIS
function im_ = doColorMap(im, colormap_)
DESCRIPTION
 doColorMap : ?
 INPUT :
       im : image
       colormap : coloramp to be used for image (default jet)
 OUTPUT :
       im_ :
 Copyright (C) 2016 Wiggins Lab
 University of Washington, 2016
 This file is part of SuperSeggerOpti.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
colorize colorize : creates an image, with defined mask, colormap, and background
makeConsIm makeConsIm : Computes consensus fluorescence localization from cells in a cell files
makeFrameMosaic makeFrameMosaic: Creates a tower for a single cell.
makeKymoMosaic makeKymoMosaic creates a mosaic kymograph of multiple cells.
makeKymographC makeKymographC creates a kymograph for given cell.
pcanal4 Copyright (C) 2016 Wiggins Lab
showDA4new showDA4new : produces the trackOptiView image according to clist and
towerMergeImages towerMergeImages
SOURCE CODE
function im_ = doColorMap(im, colormap_)
% doColorMap : ?
%
% INPUT :
%       im : image
%       colormap : coloramp to be used for image (default jet)
%
% OUTPUT :
%       im_ :
%
% Copyright (C) 2016 Wiggins Lab
% University of Washington, 2016
% This file is part of SuperSeggerOpti.
ss  = size(im);
im_ = im;
im_ = im_(:);
im_ = colormap_(im_+1,:);
im_ = reshape(im_, [ss,3]);
end