function segInfoNames = getSegInfoNames()
% getSegInfoNames : names for the 19 parameters used to calculate the segments' scores.

segInfoNames = { '1 : Minimum phase intensity on the segment', ...
    '2: Mean phase intensity on the segment', ...
    '3: Area of the segment', ...
    '4: Mean second d of the phase normal to the segment', ...
    '5: Second d of the phase normal to the segment at the min pixel', ...
    '6: Second d of the phase parallel to the segment at the min pixel', ...
    '7: min area of neighboring regions', ...
    '8: max area of neighboring regions',...
    '9: min length of the minor axis of the neighboring regions',...
    '10: max length of the minor axis of the neighboring regions',...
    '11: min length of the major axis of the neighboring regions', ...
    '12: max length of the major axis of the neighboring regions', ...
    '13: length of minor axis', ...
    '14: length of major axis', ...
    '15: square of length of major axis', ...
    '16: max length of region projected onto the major axis segment',...
    '17: min length of region projected onto the major axis segment', ...
    '18: max length of region projected onto the minor axis segment',...
    '19: min length of region projected onto the minor axis segment', ...
    };

segInfoNames = segInfoNames'
end