Description of segmentScoreFun
Home > SuperSeggerRelease > segmentation > segmentScoreFun.m
segmentScoreFun
PURPOSE
segmentScoreFun calls a function to calculates the score of the segment.
SYNOPSIS
function score = segmentScoreFun(info, A)
DESCRIPTION
 segmentScoreFun calls a function to calculates the score of the segment.
 to determine if the segment will be included.
 INPUT :
       info : has information about the segment (look at superSeggerOpti for
       more info)
       A : scoring vector optimized for different cells and imaging conditions
 OUTPUT :
       score : segment score, a score below 0 is set off.
 Copyright (C) 2016 Wiggins Lab
 University of Washington, 2016
 This file is part of SuperSeggerOpti.
CROSS-REFERENCE INFORMATION
This function calls:
segmentScoreFunMatrix segmentScoreFun calculates the score of a segment.
This function is called by:
superSeggerOpti superSeggerOpti generates the initial segmentation of rod-shaped cells.
superSeggerOptiP superSeggerOptiP generates the initial segmentation of rod-shaped cells.
SOURCE CODE
function score = segmentScoreFun(info, A)
% segmentScoreFun calls a function to calculates the score of the segment.
% to determine if the segment will be included.
%
% INPUT :
%       info : has information about the segment (look at superSeggerOpti for
%       more info)
%       A : scoring vector optimized for different cells and imaging conditions
% OUTPUT :
%       score : segment score, a score below 0 is set off.
%
% Copyright (C) 2016 Wiggins Lab
% University of Washington, 2016
% This file is part of SuperSeggerOpti.
score = segmentScoreFunMatrix(info,A);
end