Description of trackOptiView
Home > SuperSeggerOpti_Release > viz > trackOptiView.m
trackOptiView
PURPOSE
trackOptiView provides visulization of the segmented data.
SYNOPSIS
function trackOptiView(dirname,file_filter,err_flag)
DESCRIPTION
 trackOptiView provides visulization of the segmented data.
 It has a lot of options such as :
 f : Toggle between phase and fluorescence view
 x# :  Switch xy dir #
 t  : Show Cell Numbers
 r  : Show/Hide Region Outlines
 o  : Show Consensus
 K  : Kymograph Mosaic
 h# : Tower for Cell #
 g  : Make Gate
 Clear : Clear all Gates
 c  : Reset Plot to Default View'
 s  : Show Fluor Foci
 #  : Go to Frame Number #
 CC : Use Complete Cell Cycles
 F : Find Cell Number #
 p  : Show/Hide Cell Poles
 H# : Show Kymograph for Cell #
 Z  : Cell Towers Mosaic
 G  : Gate All Cell Files
 Movie : Export Movie Frames
 INPUT :
       dirname : directory that contains file segemented by supeSegger
       file_filter :
       err_flag :
 Copyright (C) 2016 Wiggins Lab
 University of Washington, 2016
 This file is part of SuperSeggerOpti.
CROSS-REFERENCE INFORMATION
This function calls:
makeConsIm makeConsIm Computes consensus fluorescence localization from cells in a cell files
makeFrameMosaic
makeFrameStripeMosaic
makeKymoMosaic
makeKymographC
showDA4new Copyright (C) 2016 Wiggins Lab
This function is called by:
SUBFUNCTIONS
function data = loaderInternal(filename, clist)
function [nameInfo] = getDirStruct(dirname)
function padStr = getPadSize(dirname)
function ixy = intGetNum(str_xy)
function [data_r, data_c, data_f] = intLoadData(dirname,
function val = AD_FLAG()
function val = SD_FLAG()
function val = ND_FLAG()
function intDispError(data_c, FLAGS)
function FLAGS = intSetDefaultFlags()
function intCons(dirname0, contents_xy, dircons, setHeader, CONST)
SOURCE CODE
function trackOptiView(dirname,file_filter,err_flag)
% trackOptiView provides visulization of the segmented data.
%
% It has a lot of options such as :
% f : Toggle between phase and fluorescence view
% x# :  Switch xy dir #
% t  : Show Cell Numbers
% r  : Show/Hide Region Outlines
% o  : Show Consensus
% K  : Kymograph Mosaic
% h# : Tower for Cell #
% g  : Make Gate
% Clear : Clear all Gates
% c  : Reset Plot to Default View'
% s  : Show Fluor Foci
% #  : Go to Frame Number #
% CC : Use Complete Cell Cycles
% F : Find Cell Number #
% p  : Show/Hide Cell Poles
% H# : Show Kymograph for Cell #
% Z  : Cell Towers Mosaic
% G  : Gate All Cell Files
% Movie : Export Movie Frames
%
% INPUT :
%       dirname : directory that contains file segemented by supeSegger
%       file_filter :
%       err_flag :
%
% Copyright (C) 2016 Wiggins Lab
% University of Washington, 2016
% This file is part of SuperSeggerOpti.
%% Load Constants and Initialize Flags
hf = figure(1);
clf;
%set(hf, 'Color', [0.1,0.1,0.1]);
mov = struct;
CONST = [];
touch_list = [];
if nargin<2 || isempty(file_filter);
    file_filter = '*err.mat';
end
if nargin<3 || isempty(err_flag);
    err_flag = 1;
end
FLAGS.err_flag = err_flag;
if ~exist('strip_flag');
    strip_flag = 1;
end
% Add slash to the file name if it doesn't exist
if(nargin<1 || isempty(dirname))
    dirname=uigetdir()
    dirname=[dirname,filesep];
else
    if dirname(end)~=filesep
        dirname=[dirname,filesep];
    end
end
D_FLAG = [];
n_char    = numel(dirname);
seg_pos   = strfind(dirname, ['seg',filesep]);
if (n_char - seg_pos) == (numel(['seg',filesep])-1)
    disp( 'seg mode' );
    D_FLAG = SD_FLAG;
else
    if exist( [dirname,filesep,'raw_im'],'dir')
        D_FLAG = AD_FLAG;
    else
        D_FLAG = ND_FLAG;
    end
end
dirname0 = dirname;
% load flags if they already exist to maintain state between launches
filename_flags = [dirname0,'.trackOptiView.mat'];
if  (D_FLAG == AD_FLAG) && exist(filename_flags, 'file')
    load(filename_flags);
else
    FLAGS = intSetDefaultFlags();
    error_list = [];
    nn = 1;
    dirnum = 1;
end
contents = [];
% Load info from one of the xy directories. dirnum tells you which one. If
% you quit the program in an xy dir, it goes to that xy dir.
clist = [];
if D_FLAG == AD_FLAG
    contents_xy =dir([dirname, 'xy*']);
    % Load up the aska set name from the file header.mat
    setHeaderFileName = [dirname,'header.mat'];
    if exist( setHeaderFileName, 'file' );
        setHeader = load( setHeaderFileName );
        setHeader = setHeader.header;
    else
        setHeader = [];
    end
    try
        dircons = [dirname0,'consensus',filesep];
        mkdir( dircons );
    end
    num_xy = numel(contents_xy);
    if ~num_xy
        disp('no xy dirs');
        return;
    else
        if isdir([dirname0,contents_xy(dirnum).name,filesep,'seg_full'])
            dirname = [dirname0,contents_xy(dirnum).name,filesep,'seg_full',filesep];
        else
            dirname = [dirname0,contents_xy(dirnum).name,filesep,'seg',filesep];
        end
        dirname_cell = [dirname0,contents_xy(dirnum).name,filesep,'cell',filesep];
        dirname_xy = [dirname0,contents_xy(dirnum).name,filesep];
        % Open clist if it exists
        clist_name = [dirname0,contents_xy(dirnum).name,filesep,'clist.mat'];
        if exist( clist_name, 'file' )
            clist = load([dirname0,contents_xy(dirnum).name,filesep,'clist.mat']);
        else
            clist = [];
        end
        ixy = intGetNum( contents_xy(dirnum).name );
        header = ['xy',num2str(ixy),': '];
    end
    nameInfo = [];
elseif D_FLAG == ND_FLAG
    [nameInfo] = getDirStruct( dirname0 );
    num_xy = numel(nameInfo.nxy);
    header = ['xy',num2str(dirnum),': '];
end
FLAGS.D_flag  = D_FLAG;
if (D_FLAG == AD_FLAG) || (D_FLAG == SD_FLAG)
    contents=dir([dirname, file_filter]);
    num_im = length(contents);
else
    num_im = numel(nameInfo.nt);
end
try
    CONST = load([dirname0,'CONST.mat']);
    if isfield( CONST, 'CONST' )
        CONST = CONST.CONST;
    end
catch
    disp(['Exiting. Can''t load CONST file. Make sure there is a CONST.mat file at the root', ...
        'level of the data directory.']);
    return
end
if nn > num_im
    nn = num_im;
end
runFlag = (nn<=num_im);
first_flag = 1;
% This flag controls whether you reload from file
resetFlag = true;
FLAGS.e_flag = 0 ;
%% Run the main loop... and run it while the runFlag is true.
while runFlag
    % load current frame
    if resetFlag
        resetFlag = false;
        %tic
        [data_r, data_c, data_f] = intLoadData( dirname, ...
            D_FLAG, contents, nn, num_im, nameInfo, clist, dirnum);
        %toc
    end
    if ~first_flag
        tmp_axis = axis;
    else
        try
            imshow( data_c.phase );
        end
    end
    %tic
    %try
    showDA4new( data_c, data_r, data_f, FLAGS, clist, CONST);
    %toc
    %end
    if FLAGS.c_flag && ~first_flag
        axis( tmp_axis );
    end
    first_flag = false;
    % Main Menu
    disp('-----------------------------------------------------------');
    disp('SuperSegger Data Viewer');
    disp(' ');
    disp('q  : To quit                    c  : Reset Plot to Default View');
    disp('f  : Toggle Phase/Fluor         s  : Show Fluor Foci           ');
    disp('x# : Switch xy dir #            #  : Go to Frame Number #      ');
    disp('t  : Show Cell Numbers          CC : Use Complete Cell Cycles ');
    disp('r  : Show/Hide Region Outlines  F# : Find Cell Number #       ');
    disp('o  : Show Consensus             p  : Show/Hide Cell Poles      ');
    disp('K  : Kymograph Mosaic           H# : Show Kymograph for Cell #');
    disp('h# : Tower for Cell #           Z  : Cell Towers Mosaic        ');
    disp('g  : Make Gate                  G  : Gate All Cell Files       ');
    disp('Clear : Clear all Gates         Movie : Export Movie Frames   ');
    disp(' ');
    disp('              k : Enter debugging mode                      ');
    disp('-----------------------------------------------------------')
    disp(' ');
    % if you loaded segmented data
    if D_FLAG ~= ND_FLAG
        % show the master error list.
        if FLAGS.err_flag
            if isempty(error_list)
                error_list = trackOptiGetErrorListDisk( dirname, [] );
            end
            disp(error_list);
        end
        % show errors in this frame.
        if FLAGS.e_flag
            intDispError( data_c, FLAGS );
        end
    end
    if ~isempty( touch_list );
        disp('Warning! Frames touched. Run re-link.');
        touch_list
    end
    disp([header, 'Frame num [1...',num2str(num_im),']: ',num2str(nn)]);
    c = input(':','s')
    if isempty(c)
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        %
        % LIST OF COMMANDS
        %
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % Quit Command
    elseif c(1) == 'q'
        % This is the quit command
        if D_FLAG == AD_FLAG
            try
                save( [dirname0,contents_xy(dirnum).name,filesep,'clist.mat'],'-STRUCT','clist');
            catch
                disp('Error saving clist file.');
            end
        end
        runFlag = 0  ;
        % Toggle Between Full Cell Cycles
    elseif strcmp(c,'CC')
        CONST.view.showFullCellCycleOnly = ~CONST.view.showFullCellCycleOnly ;
        if CONST.view.showFullCellCycleOnly
            disp('Only including complete Cell Cycles (press any key)')
            pause
        else
            disp('Including Incomplete Cell Cycles (press any key)')
            pause
        end
        % Find Single Cells
    elseif c(1) == 'F'
        if numel(c) > 1
            find_num = floor(str2num(c(2:end)));
            if FLAGS.v_flag
                regnum = find( data_c.regs.ID == find_num);
                if ~isempty( regnum )
                    plot(data_c.CellA{regnum}.coord.r_center(1),...
                        data_c.CellA{regnum}.coord.r_center(2), ...
                        'yx','MarkerSize',100);
                else
                    disp('coundt fidn that cell');
                end
            else
                if (find_num <= data_c.regs.num_regs) && (find_num >0)
                    plot(data_c.CellA{find_num}.coord.r_center(1),...
                        data_c.CellA{find_num}.coord.r_center(2), ...
                        'yx','MarkerSize',100);
                else
                    disp( 'Out of range' );
                end
            end
            input('Press any key','s');
        end
        % Change xy positions
    elseif c(1) == 'x'
        if D_FLAG ~= SD_FLAG
            if numel(c)>1
                c = c(2:end);
            else
                for ll = 1:num_xy
                    if D_FLAG ~= ND_FLAG
                        disp( [num2str(ll),': ',contents_xy(ll).name] );
                    else
                        disp( [num2str(ll),': xy',num2str(nameInfo.nxy(ll))] );
                    end
                end
                c = input(':','s')
            end
            ll_ = floor(str2num(c));
            if ~isempty(ll_) && (ll_>=1) && (ll_<=num_xy)
                if D_FLAG ~= ND_FLAG
                    if D_FLAG == AD_FLAG
                        try
                            save( [dirname0,contents_xy(dirnum).name,filesep,'clist.mat'],'-STRUCT','clist');
                        catch
                            disp( 'Error writing clist file.');
                        end
                    end
                    dirnum = ll_;
                    if isdir([dirname0,contents_xy(dirnum).name,filesep,'seg_full'])
                        dirname = [dirname0,contents_xy(ll_).name,filesep,'seg_full',filesep];
                    else
                        dirname = [dirname0,contents_xy(ll_).name,filesep,'seg',filesep];
                    end
                    dirname_cell = [dirname0,contents_xy(ll_).name,filesep,'cell',filesep];
                    dirname_xy = [dirname0,contents_xy(ll_).name,filesep];
                    ixy = intGetNum( contents_xy(dirnum).name );
                    header = ['xy',num2str(ixy),': '];
                    contents=dir([dirname, file_filter]);
                    error_list = [];
                    clist = load([dirname0,contents_xy(ll_).name,filesep,'clist.mat']);
                else
                    dirnum = nameInfo.nxy(ll_);
                    header = ['xy',num2str(dirnum),': '];
                end
            end
            resetFlag = true;
        else
            disp( 'Not supported in this mode.' );
        end
        % Show/Hide Region Outlines
    elseif c(1) == 'r'
        FLAGS.P_flag = ~FLAGS.P_flag;
        % Reset Plot to Default View
    elseif strcmp(c,'c')
        FLAGS.c_flag = ~FLAGS.c_flag;
        clf;
        first_flag = 1;
        % Toggle Between Fluorescence and Phase Images
    elseif c(1) == 'f'
        FLAGS.f_flag = ~FLAGS.f_flag;
        % Gate Cells
    elseif c(1) == 'g'
        disp('Choose gating characteristic')
        disp(clist.def')
        cc = input('Gate Number(s) [ ] :','s') ;
        tmp_clist = gateMake(clist,str2num(cc)) ;
        clist = tmp_clist ;
        clf;
        first_flag = 1;
        % Clear All Gates
    elseif strcmp(c,'Clear')
        clist.gate = [] ;
        clf;
        first_flag = 1;
        % Gate Cell Files
    elseif c(1) == 'G'
        header = 'trackOptiView: ';
        trackOptiGateCellFiles(dirname,dirname_cell,CONST, header, clist);
        % Gate All XY Positions
    elseif c(1) == 'C'
        if D_FLAG == AD_FLAG
            if ~isfield( clist, 'gate' );
                clist.gate = [];
            end
            for ll_ = 1:num_xy
                filename = [dirname0,contents_xy(ll_).name,filesep,'clist.mat'];
                clist_tmp = gate(load( filename ));
                if  ll_ == 1
                    clist_comp =clist_tmp;
                else
                    clist_comp.data = [clist_comp.data; clist_tmp.data];
                end
            end
            save( [dirname0,'clist_comp.mat'], '-STRUCT', 'clist_comp' );
        else
            disp('Not supported');
        end
        % Show Cell Numbers
    elseif c(1) == 't'
        FLAGS.t_flag = ~FLAGS.t_flag;
        % Show Fluorescent Foci Fits
    elseif c(1) == 's'
        FLAGS.s_flag = ~FLAGS.s_flag;
        % Show Cell Poles
    elseif c(1) == 'p'
        FLAGS.p_flag = ~FLAGS.p_flag;
        % Enter Debugging Mode
    elseif c(1) == 'k'
        tmp_axis = axis;
        disp('Type "return" to exit debugging mode')
        keyboard
        resetFlag = true;
        clf;
        axis( tmp_axis );
        % Make Kymograph Mosaic for All Cells
    elseif c(1) == 'K'
        if D_FLAG == AD_FLAG
            tmp_axis = axis;
            clf;
            makeKymoMosaic( [dirname_cell], CONST );
            disp('press enter to continue.');
            pause;
            axis(tmp_axis);
        else
            disp( 'Not supported in this mode.' );
        end
        % Show Cell Towers for All Cells
    elseif c(1) == 'Z'
        if D_FLAG == AD_FLAG
            tmp_axis = axis;
            clf;
            if numel(c) > 1
                ll_ = floor(str2num(c(2:end)));
            else
                ll_ = [];
            end
            makeFrameStripeMosaic( [dirname_cell], CONST, ll_,true );
            axis equal
            disp('press enter to continue.');
            pause;
            axis(tmp_axis);
        else
            disp( 'Not supported in this mode.' );
        end
        % Show Consensus for this XY if exists or Calculate new one
    elseif c(1) == 'o'
        intCons(dirname0, contents_xy(ixy), dircons, setHeader, CONST)%
        % Calculate Consensus for all XY
    elseif c(1) == 'Y'
        tmp_axis = axis;
        clf;
        parfor iii = 1:num_xy
            try
                intCons(dirname0, contents_xy(iii), dircons, setHeader, CONST)
            catch
                disp( ['Failed on: ', contents_xy(iii).name] );
            end
        end
        FLAGS__.v_flag = 1;
        FLAGS__.m_flag = 0;
        FLAGS__.t_flag = 1;
        FLAGS__.T_flag = 0;
        FLAGS__.ID_flag = 1;
        FLAGS__.P_flag = 1;
        FLAGS__.e_flag = 0;
        FLAGS__.f_flag = 1;
        FLAGS__.s_flag = 1;
        FLAGS__.p_flag = 0;
        FLAGS__.c_flag = 1;
        FLAGS__.lyse_flag = 0;
        FLAGS__.err_flag = 0;
        FLAGS__.D_flag = 0;
        for iii = 1:num_xy
            try
                iii
                nn__ = 10;
                if isdir([dirname0,contents_xy(iii).name,filesep,'seg_full'])
                    dirname__ = [dirname0,contents_xy(iii).name,filesep,'seg_full',filesep];
                else
                    dirname__ = [dirname0,contents_xy(iii).name,filesep,'seg',filesep];
                end
                dirname_cell__ = [dirname0,contents_xy(iii).name,filesep,'cell',filesep];
                dirname_xy__ = [dirname0,contents_xy(iii).name,filesep];
                ixy__ = intGetNum( contents_xy(iii).name );
                header__ = ['xy',num2str(ixy),': '];
                contents__=dir([dirname__, file_filter]);
                error_list = [];
                clist__ = load([dirname0,contents_xy(iii).name,filesep,'clist.mat']);
                nameInfo__ = getDirStruct( dirname0 );
                [data_r__, data_c__, data_f__] = intLoadData( dirname__, ...
                    D_FLAG, contents__, nn__, num_im, nameInfo__, clist__, iii);
                im_tmp = showDA4new( data_c__, data_r__, data_f__, FLAGS__, clist__, CONST);
                imwrite( im_tmp, [dircons, 'field_', setHeader, '_', num2str(ixy__,'%02d'), '.tif'], 'tif' );
            catch
                disp(['error with ',num2str(iii)]);
            end
        end
        figure(1);
        axis equal
        figure(1);
        axis(tmp_axis);
        % Cell Tower for Single Cell
    elseif c(1) == 'h'
        if D_FLAG == AD_FLAG
            if numel(c) > 1
                comma_pos = findstr(c,',');
                if isempty(comma_pos)
                    ll_ = floor(str2num(c(2:end)));
                    xdim__ = [];
                else
                    ll_ = floor(str2num(c(2:comma_pos(1))));
                    xdim__ = floor(str2num(c(comma_pos(1):end)));
                end
                padStr = getPadSize( dirname_cell );
                if ~isempty( padStr )
                    data_cell = [];
                    filename_cell_C = [dirname_cell,'Cell',num2str(ll_,padStr),'.mat']
                    filename_cell_c = [dirname_cell,'cell',num2str(ll_,padStr),'.mat']
                    if exist(filename_cell_C, 'file' )
                        filename_cell = filename_cell_C;
                    elseif exist(filename_cell_c, 'file' )
                        filename_cell = filename_cell_c;
                    else
                        filename_cell = [];
                    end
                    if isempty( filename_cell )
                        disp( ['Files: ',filename_cell_C,' and ',filename_cell_c,' do not exist.']);
                    else
                        try
                            data_cell = load( filename_cell );
                        catch
                            disp(['Error loading: ', filename_cell] );
                        end
                        if ~isempty( data_cell )
                            tmp_axis = axis;
                            clf;
                            im_tmp = makeFrameMosaic(data_cell, CONST, xdim__);
                            disp('Press enter to continue');
                            pause;
                            axis(tmp_axis);
                        end
                    end
                end
            end
        else
            disp( 'Not supported in this mode.' );
        end
        % Show Kymograph for Single Cell
    elseif c(1) == 'H'
        if D_FLAG == AD_FLAG
            if numel(c) > 1
                ll_ = floor(str2num(c(2:end)));
                padStr = getPadSize( dirname_cell );
                if ~isempty( padStr )
                    data_cell = [];
                    filename_cell_C = [dirname_cell,'Cell',num2str(ll_,padStr),'.mat']
                    filename_cell_c = [dirname_cell,'cell',num2str(ll_,padStr),'.mat']
                    if exist(filename_cell_C, 'file' )
                        filename_cell = filename_cell_C;
                    elseif exist(filename_cell_c, 'file' )
                        filename_cell = filename_cell_c;
                    else
                        filename_cell = [];
                    end
                    if isempty( filename_cell )
                        disp( ['Files: ',filename_cell_C,' and ',filename_cell_c,' do not exist.']);
                    else
                        try
                            data_cell = load( filename_cell );
                        catch
                            disp(['Error loading: ', filename_cell] );
                        end
                        if ~isempty( data_cell )
                            tmp_axis = axis;
                            clf;
                            makeKymographC(data_cell, 1, CONST );
                            ylabel('Long Axis (pixels)');
                            xlabel('Time (frames)' );
                            disp('Press enter to continue');
                            pause;
                            axis(tmp_axis);
                        end
                    end
                end
            end
        else
            disp( 'Not supported in this mode.' );
        end
        % Make Time-Lapse Images for Movies
    elseif strcmp(c,'Movie')
        setAxis = axis;
        nn_old = nn;
        z_pad = ceil(log(num_im)/log(10));
        movdir = 'mov';
        if ~exist( movdir, 'dir' )
            mkdir( movdir );
        end
        file_tmp = ['%0',num2str(z_pad),'d'];
        for nn = 1:num_im
            [data_r, data_c, data_f] = intLoadData( dirname, ...
                D_FLAG, contents, nn, num_im, nameInfo, clist, dirnum);
            %clf;
            tmp_im = showDA4new( data_c,data_r, data_f, FLAGS, clist, CONST);
            %axis(setAxis);
            drawnow;
            disp( ['Frame number: ', num2str(nn)] );
            %tmp_im = frame2im(getframe);
            imwrite( tmp_im, [movdir,filesep,'mov',sprintf(file_tmp,nn),'.tif'], 'TIFF', 'Compression', 'none' );
        end
        nn = nn_old;
        resetFlag = true;
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        %
        % Developer Tools (use at own risk)
        %
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % Show Error List
    elseif c(1) == 'e'
        FLAGS.e_flag = ~FLAGS.e_flag;
        % Toggle between cell view and region view
    elseif c(1) == 'v'
        FLAGS.v_flag = ~FLAGS.v_flag;
        % Edit Segments
    elseif strcmp(c,'editSegs')
        segsTLEdit( dirname, nn);
        % Re-Link
    elseif strcmp(c, 'relink')
        if ispc
            eval(['!del ',dirname_cell,'*.mat'      ]);
            eval(['!del ',dirname,     '*trk.mat*'  ]);
            eval(['!del ',dirname,     '*err.mat*'  ]);
            eval(['!del ',dirname,     '.trackOpti*']);
            eval(['!del ',dirname_xy,  'clist.mat'  ]);
        else
            eval(['!\rm ',dirname_cell,'*.mat'      ]);
            eval(['!\rm ',dirname,     '*trk.mat*'  ]);
            eval(['!\rm ',dirname,     '*err.mat*'  ]);
            eval(['!\rm ',dirname,     '.trackOpti*']);
            eval(['!\rm ',dirname_xy,  'clist.mat'  ]);
        end
        % Re-Run trackOpti
        skip = 1;
        CLEAN_FLAG = false;
        header = 'trackOptiView: ';
        trackOpti(dirname_xy,skip,CONST, CLEAN_FLAG, header);
    elseif c(1) == 'n';
        if FLAGS.T_flag
            disp( 'Tight flag must be off');
        else
            x = floor(ginput(1));
            if ~isempty(x)
                ii = data_c.regs.regs_label(x(2),x(1));
                tmp_axis = axis();
                if ~ii
                    disp('missed region');
                else
                    if isfield( data_c.regs, 'ignoreError' )
                        disp(['Picked region ',num2str(ii)]);
                        data_c.regs.ignoreError(ii) = 1;
                        save([dirname,contents(nn  ).name],'-STRUCT','data_c');
                    else
                        disp( 'Ignore error not implemented for your version of trackOpti.');
                    end
                end
            end
        end
        % Reset Linking in Current Frame
    elseif strcmp(c,'link');
        if FLAGS.T_flag
            disp( 'Tight flag must be off');
        else
            disp('pick region to reset linking in the current frame');
            x = floor(ginput(1));
            if ~isempty(x)
                ii = data_c.regs.regs_label(x(2),x(1));
                tmp_axis = axis();
                if ~ii
                    disp('missed region');
                else
                    disp(['Picked region ',num2str(ii)]);
                    showDA4new( data_f,data_c, data_f, FLAGS, clist, CONST);
                    axis( tmp_axis );
                    disp( 'Click on linked cell(s). press enter to return');
                    x = floor(ginput());
                    ss = size(x);
                    list_of_regs = [];
                    for hh = 1:ss(1);
                        jj = data_f.regs.regs_label(x(hh,2),x(hh,1));
                        if jj
                            list_of_regs = [list_of_regs, jj];
                        end
                    end
                    if ~isempty(list_of_regs)
                        %list_of_regs
                        data_c.regs.ol.f{ii}    = zeros(2, 5);
                        nnn = min([5,numel(list_of_regs)]);
                        data_c.regs.ol.f{ii}(1,1:nnn) = 1;
                        data_c.regs.ol.f{ii}(2,1:nnn) = list_of_regs(1:nnn);
                        data_c.regs.map.f{ii}   = list_of_regs;
                        data_c.regs.error.f(ii) = double(numel(list_of_regs)>1);
                        data_c.regs.ignoreError(ii) = 1;
                        for kk = list_of_regs
                            data_f.regs.ol.r{kk}     = zeros(2,5);
                            data_f.regs.ol.r{kk}(1,1)= 1/numel(list_of_regs);
                            data_f.regs.ol.r{kk}(2,1)= ii;
                            data_f.regs.dA.r(kk)     = 1/numel(list_of_regs);
                            data_f.regs.map.r{kk}    = ii;
                            data_f.regs.error.r(kk)  = double(numel(list_of_regs)>1);
                            data_f.regs.ignoreError(kk) = 1;
                        end
                        % Save files....
                        save([dirname,contents(nn  ).name],'-STRUCT','data_c');
                        save([dirname,contents(nn+1).name],'-STRUCT','data_f');
                    end
                end
            end
        end
        % ReRun Error Resolution
    elseif strcmp(c,'errRez');
        % Re-run ErRes and linking code trackOpti
        ctmp = input('Are you sure? (y/n): ','s');
        if ismember(ctmp(1),'yY')
            % Erase all stamp files after .trackOptiSetEr.mat
            contents_stamp = dir( [dirname,filesep,'.trackOpti*'] );
            num_stamp = numel( contents_stamp );
            for iii = 1:num_stamp
                if isempty( strfind( contents_stamp(iii).name,...
                        '.trackOptiLink.mat'  ) ) && ...
                        isempty( strfind( contents_stamp(iii).name,...
                        '.trackOptiErRes1.mat') ) && ...
                        isempty( strfind( contents_stamp(iii).name,...
                        '.trackOptiSetEr.mat' ) )
                    if ispc
                        eval(['!del ',dirname,filesep,...
                            contents_stamp(iii).name]);
                    else
                        eval(['!\rm ',dirname,filesep,...
                            contents_stamp(iii).name]);
                    end
                end
            end
            if ispc
                eval(['!del ',dirname_cell,'*.mat']);
                eval(['!del ',dirname_xy,'clist.mat']);
            else
                eval(['!\rm ',dirname_cell,'*.mat']);
                eval(['!\rm ',dirname_xy,'clist.mat']);
            end
            % Re-Run trackOpti
            skip = 1;
            CLEAN_FLAG = false;
            header = 'trackOptiView: ';
            trackOpti(dirname_xy,skip,CONST, CLEAN_FLAG, header);
        end
    else
        % we assume that it is a number for a frame change.
        tmp_nn = str2num(c);
        if ~isempty(tmp_nn)
            nn = tmp_nn;
            if nn > num_im;
                nn = num_im;
            elseif nn< 1
                nn = 1;
            end
        end
        resetFlag = true;
    end
end
try
    save(filename_flags, 'FLAGS', 'nn', 'dirnum', 'error_list' );
catch
    disp('Error saving flag preferences.');
end
end
% END OF MAIN FUNCTION (trackOptiView)
%% INTERNAL FUNCTIONS
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% loaderInternal
%
% Load Date and put in outline fields.
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function data = loaderInternal(filename, clist)
data = load(filename);
ss = size(data.phase);
if isfield(data, 'mask_cell')
    data.outline =  xor(bwmorph( data.mask_cell, 'dilate' ), data.mask_cell);
end
if isempty(clist)
else
    clist = gate(clist);
    data.cell_outline = false(ss);
    %tic
1000     if isfield(data, 'regs') && isfield(data.regs, 'ID')
1001
1002         ind = find(ismember(data.regs.ID,clist.data(:,1)));
1003
1004         %     for ii = ind
1005         %         [xx,yy] = getBBpad(data.regs.props(ii).BoundingBox,ss,1);
1006         %
1007         %         mask_tmp = data.regs.regs_label(yy,xx)==ii;
1008         %         data.cell_outline(yy,xx) = or(data.cell_outline(yy,xx), ...
1009         %             xor(bwmorph(mask_tmp, 'dilate'),...
1010         %             mask_tmp));
1011         %     end
1012
1013         mask_tmp = ismember(data.regs.regs_label, ind);
1014
1015         data.cell_outline = xor(bwmorph(mask_tmp, 'dilate'), mask_tmp);
1016
1017     end
1018 end
1019 %toc
1020
1021 end
1022
1023 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1024 %
1025 % getDirStruct
1026 %
1027 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1028 function [nameInfo] = getDirStruct(dirname)
1029
1030 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1031 contents = dir([dirname,filesep,'*.tif']);
1032
1033 nt  = [];
1034 nc  = [];
1035 nxy = [];
1036 nz  = [];
1037
1038 num_im = numel(contents);
1039
1040 for i = 1:num_im;
1041     nameInfo = ReadFileName(contents(i).name);
1042
1043     nt  = [nt,  nameInfo.npos(1,1)];
1044     nc  = [nc,  nameInfo.npos(2,1)];
1045     nxy = [nxy, nameInfo.npos(3,1)];
1046     nz  = [nz,  nameInfo.npos(4,1)];
1047 end
1048
1049 nt  = sort(unique(nt));
1050 nc  = sort(unique(nc));
1051 nxy = sort(unique(nxy));
1052 nz  = sort(unique(nz));
1053
1054 xyPadSize = floor(log(max(nxy))/log(10))+1;
1055 padString = ['%0',num2str(xyPadSize),'d'];
1056
1057 num_xy = numel(nxy);
1058 num_c  = numel(nc);
1059 num_z  = numel(nz);
1060 num_t  = numel(nt);
1061
1062
1063 nameInfo.nt  = nt;
1064 nameInfo.nc  = nc;
1065 nameInfo.nxy = nxy;
1066 nameInfo.nz  = nz;
1067
1068 end
1069
1070 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1071 %
1072 % getPadSize
1073 %
1074 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1075 function padStr = getPadSize(dirname)
1076
1077 contents = dir([dirname,'*ell*.mat']);
1078
1079 if numel(contents) == 0
1080     disp('No cell files');
1081     padStr = []
1082 else
1083     num_num = sum(ismember(contents(1).name,'1234567890'));
1084     padStr = ['%0',num2str(num_num),'d'];
1085 end
1086
1087 end
1088
1089
1090 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1091 %
1092 % intGetNum
1093 %
1094 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1095 function ixy = intGetNum(str_xy)
1096 ixy = str2num(str_xy(ismember(str_xy, '0123456789')));
1097 end
1098
1099
1100 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1101 %
1102 % intLoadData
1103 %
1104 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1105 function [data_r, data_c, data_f] = intLoadData(dirname, ...
1106     D_FLAG, contents, nn, num_im, nameInfo, clist, ixy)
1107
1108
1109 if (D_FLAG == AD_FLAG) || (D_FLAG == SD_FLAG)
1110
1111     %'start'
1112
1113     if (nn ==1) && (1 == num_im)
1114         data_r = [];
1115         data_c = loaderInternal([dirname,contents(nn).name], clist);
1116         data_f = [];
1117     elseif nn == 1;
1118         data_r = [];
1119         data_c = loaderInternal([dirname,contents(nn).name], clist);
1120         data_f = [];
1121         %data_f = loaderInternal([dirname,contents(nn+1).name], clist);
1122         %data_ff= loaderInternal([dirname,contents(nn+2).name]);
1123     elseif nn == num_im
1124         %data_r = loaderInternal([dirname,contents(nn-1).name], clist);
1125         data_r = [];
1126         data_c = loaderInternal([dirname,contents(nn).name], clist);
1127         data_f = [];
1128         %data_ff= [];
1129     elseif nn == num_im-1
1130         %data_r = loaderInternal([dirname,contents(nn-1).name], clist);
1131         data_r = [];
1132         data_c = loaderInternal([dirname,contents(nn).name], clist);
1133         data_f = [];
1134         %data_f = loaderInternal([dirname,contents(nn+1).name], clist);
1135         %data_ff= [];
1136     else
1137
1138         if 1
1139             data_r = loaderInternal([dirname,contents(nn-1).name], clist);
1140             data_f = loaderInternal([dirname,contents(nn+1).name], clist);
1141         else
1142             data_r = [];
1143             data_f = [];
1144         end
1145         data_c = loaderInternal([dirname,contents(nn).name], clist);
1146         %data_ff= loaderInternal([dirname,contents(nn+1).name]);
1147     end
1148
1149     %'finish'
1150
1151 else
1152
1153     data_f = [];
1154     data_r = [];
1155     data_c = [];
1156
1157     % it  = nameInfo.npos(1,1);
1158     % ic  = nameInfo.npos(2,1);
1159     % ixy = nameInfo.npos(3,1);
1160     % iz  = nameInfo.npos(4,1);
1161
1162     nameInfo.npos(1,1) = nameInfo.nt(nn);
1163     nameInfo.npos(3,1) = nameInfo.nxy(ixy);
1164     nameInfo.npos(2,1) = 1;
1165     nameInfo.npos(4,1) = 1;
1166
1167     name = [dirname,MakeFileName(nameInfo)];
1168
1169
1170     data_c.phase = imread(name);
1171     for ic = nameInfo.nc(2:end)
1172
1173         nameInfo.npos(2,1) = nameInfo.nc(ic);
1174         name = [dirname,MakeFileName(nameInfo)];
1175
1176         tmp = imread(name);
1177         data_c = setfield(data_c, ['fluor',num2str(ic-1)], tmp);
1178     end
1179 end
1180
1181
1182
1183
1184
1185 end
1186
1187 % Do directory handling
1188 % Sense whether trackOptiView is being launched with an align of seg
1189 % directory.
1190 function val = AD_FLAG()
1191 val = 0;
1192 end
1193 function val = SD_FLAG()
1194 val = 1;
1195 end
1196 function val = ND_FLAG()
1197 val = 2;
1198 end
1199
1200 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1201 %
1202 % intDispError
1203 %
1204 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1205 function intDispError(data_c, FLAGS)
1206
1207 for kk = 1:data_c.regs.num_regs
1208     if isfield(data_c,'regs') &&...
1209             isfield(data_c.regs, 'error') && ...
1210             isfield(data_c.regs.error,'label') && ...
1211             ~isempty(data_c.regs.error.label{kk})
1212         if FLAGS.v_flag && isfield(data_c.regs, 'ID')
1213             disp(['Cell: ', num2str(data_c.regs.ID(kk)), ', ', ...
1214                 data_c.regs.error.label{kk}]);
1215         else
1216             disp([ data_c.regs.error.label{kk}]);
1217         end
1218     end
1219 end
1220 end
1221
1222 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1223 %
1224 % intSetDefaultFlags
1225 %
1226 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1227 function FLAGS = intSetDefaultFlags()
1228
1229 FLAGS.v_flag  = 1;
1230 FLAGS.m_flag  = 0;
1231 FLAGS.t_flag  = 0;
1232 FLAGS.T_flag  = 0;
1233 FLAGS.ID_flag = 1;
1234 FLAGS.P_flag  = 1;
1235 FLAGS.e_flag  = 0;
1236 FLAGS.f_flag  = 0;
1237 FLAGS.s_flag  = 1;
1238 FLAGS.p_flag  = 0;
1239 FLAGS.c_flag  = 1;
1240 FLAGS.lyse_flag = false;
1241 FLAGS.err_flag = false;
1242
1243 end
1244
1245
1246 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1247 %
1248 % intSetDefaultFlags
1249 %
1250 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1251 function intCons(dirname0, contents_xy, dircons, setHeader, CONST)
1252 %try
1253
1254 ixy = intGetNum(contents_xy.name);
1255 header = ['xy',num2str(ixy),': '];
1256
1257 if exist([dircons, 'consColor_', setHeader, '_', num2str(ixy,'%02d'), '.tif'])
1258     disp('Consensus Already Calculated')
1259     imColor = imread([dircons, 'consColor_', setHeader, '_', num2str(ixy,'%02d'), '.tif']);
1260     figure(1)
1261     clf
1262     imshow(imColor);
1263     disp('Press any key to continue')
1264     pause
1265
1266 else
1267
1268     disp('No Images Found.')
1269     disp('Calculate New Consensus?')
1270     d = input('[y/n]:','s');
1271
1272     if strcmp(d,'y')
1273
1274         if isdir([dirname0,contents_xy.name,filesep,'seg_full'])
1275             dirname = [dirname0,contents_xy.name,filesep,'seg_full',filesep];
1276         end
1277
1278         dirname_cell = [dirname0,contents_xy.name,filesep,'cell',filesep];
1279
1280         disp(['Doing ',num2str(ixy)]);
1281
1282         %makeFrameStripeMosaicCenter([dirname_cell], CONST, ll_);
1283         %[imTot, imColor, imBW, imInv, kymo, kymoMask, I ] = ...
1284         %    makeFrameStripeMosaicCenterMag([dirname_cell], CONST, [], 0, 0);
1285         %[imTot, imColor, imBW, imInv, kymo, kymoMask, I ] = ...
1286         %    makeFrameStripeMosaicCenter2([dirname_cell], CONST, ll_);
1287         [imTot, imColor, imBW, imInv, kymo, kymoMask, I, jjunk, jjunk, imTot10 ] = ...
1288             makeConsIm([dirname_cell], CONST, [], [], false);
1289
1290         figure(1)
1291         clf
1292         imshow(imColor)
1293
1294         disp('Press any key to continue')
1295         pause
1296
1297         if ~isempty(imTot)
1298             imwrite(imBW,    [dircons, 'consBW_',    setHeader, '_', num2str(ixy,'%02d'), '.tif'], 'tif');
1299             imwrite(imColor, [dircons, 'consColor_', setHeader, '_', num2str(ixy,'%02d'), '.tif'], 'tif');
1300             imwrite(imInv,   [dircons, 'consInv_',   setHeader, '_', num2str(ixy,'%02d'), '.tif'], 'tif');
1301             imwrite(imTot10,   [dircons, 'typical_',   setHeader, '_', num2str(ixy,'%02d'), '.tif'], 'tif');
1302
1303             %figure(99);
1304             %print('-depsc', [dircons, 'dyn', num2str(ixy,'%02d'), '.eps']);
1305
1306             save([dircons, 'fits', num2str(ixy,'%02d'), '.mat'], 'I');
1307         else
1308
1309             disp(['Found no cells in ', dirname_cell, '.']);
1310         end
1311
1312     else
1313
1314         return
1315
1316     end
1317     %catch
1318     %disp(['Error ',num2str(ixy)]);
1319
1320 end
1321 end