function names = getRegNames3()
% getRegNames3 contains the CONST.regionScoreFun.names
% it is not used anywhere in the code. It is mostly for your information.


names = { 'long axis: ', ...
    'short axis mean: ', ...
    'neck width: ', ...
    'short axis max: ', ...
    'short axis var: ', ...
    '<width sin pi s/S >: ', ...
    '<width sin pi 2s/S>: ', ...
    '<width sin pi 3s/S>: ', ...
    'RoundIndOver: ', ...
    'RoundIndUnder ', ...
    'Area: ', ....
    'max dtheta^2: ', ...
    '<theta sin pi s/2S >: ', ...
    '<theta sin pi s/S  >: ', ...
    '<theta sin pi 3s/2S>: ', ...
    '<theta sin pi 2s/S >: ', ...
    '1/long axis: ', ...
    '1/mean short axis: ',...
    'Min End Width: ',...
    'round end min: ',...
    'round end max: '};


end
