function names = getRegNames3()
% getRegNames3 : contains the names of the parameters in the E matrix.
% The E matrix is the coefficients used to score the regions as a 
% constant + linear function + quadratic function of the parameters.
% There are 21 parameters but the E matrix has 22 because the first column
% of the parameters is 1 to account for linear + constant.

names = { 'long axis: ', ...
    'short axis mean: ', ...
    'neck width: ', ...
    'short axis max: ', ...
    'short axis var: ', ...
    '<width sin pi s/S >: ', ...
    '<width sin pi 2s/S>: ', ...
    '<width sin pi 3s/S>: ', ...
    'RoundIndOver: ', ...
    'RoundIndUnder ', ...
    'Area: ', ....
    'max dtheta^2: ', ...
    '<theta sin pi s/2S >: ', ...
    '<theta sin pi s/S  >: ', ...
    '<theta sin pi 3s/2S>: ', ...
    '<theta sin pi 2s/S >: ', ...
    '1/long axis: ', ...
    '1/mean short axis: ',...
    'Min End Width: ',...
    'round end min: ',...
    'round end max: '};


end
