function segInfoNames = getSegInfoNames()
% getSegInfoNames : names for the 19 parameters used to calculate the 
% segments' scores.
%
% OUTPUT : 
%      segInfoNames : names of parameters for segments' scorings.
%
% Copyright (C) 2016 Wiggins Lab 
% Written by Stella Stylianidou
% University of Washington, 2016
% This file is part of SuperSegger.
% 
% SuperSegger is free software: you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
% 
% SuperSegger is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with SuperSegger.  If not, see <http://www.gnu.org/licenses/>.

segInfoNames = { '1 : Minimum phase intensity on the segment', ...
    '2: Mean phase intensity on the segment', ...
    '3: Area of the segment', ...
    '4: Mean second d of the phase normal to the segment', ...
    '5: Second d of the phase normal to the segment at the min pixel', ...
    '6: Second d of the phase parallel to the segment at the min pixel', ...
    '7: min area of neighboring regions', ...
    '8: max area of neighboring regions',...
    '9: min length of the minor axis of the neighboring regions',...
    '10: max length of the minor axis of the neighboring regions',...
    '11: min length of the major axis of the neighboring regions', ...
    '12: max length of the major axis of the neighboring regions', ...
    '13: length of minor axis', ...
    '14: length of major axis', ...
    '15: square of length of major axis', ...
    '16: max length of region projected onto the major axis segment',...
    '17: min length of region projected onto the major axis segment', ...
    '18: max length of region projected onto the minor axis segment',...
    '19: min length of region projected onto the minor axis segment', ...
    };

segInfoNames = segInfoNames'
end